# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=10)),
                ('query', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='TakeupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takenup', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QueryModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.UserModel')),
            ],
        ),
    ]
