# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_usermodel_points'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=10000)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.KeyModel')),
            ],
        ),
        migrations.CreateModel(
            name='TakeupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takenup', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QueryModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.UserModel')),
            ],
        ),
    ]
