# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='language',
            field=models.CharField(default='English', max_length=120),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='key',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
