# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20170715_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
